const express=require('express');const http=require('http');const {WebSocketServer}=require('ws');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server});const rooms=new Map();
app.use(express.json({limit:'100kb'}));app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});app.use(express.static('public'));
const id=()=>Math.random().toString(36).slice(2,10);
const clean=String;
const list=()=>[...rooms.values()].filter(r=>r.public).map(r=>({id:r.id,title:r.title,pickedId:r.pickedId,thumb:r.thumb,clients:r.clients.size,createdAt:r.createdAt}));
function broadcast(r,p,except){const s=JSON.stringify(p);for(const c of r.clients)if(c!==except&&c.readyState===1)c.send(s)}
wss.on('connection',ws=>{ws.roomId=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='join-room'){const r=rooms.get(String(m.roomId||''));if(!r)return ws.send(JSON.stringify({type:'error',error:'Sala não encontrada'}));if(ws.roomId&&rooms.has(ws.roomId))rooms.get(ws.roomId).clients.delete(ws);ws.roomId=r.id;r.clients.add(ws);ws.send(JSON.stringify({type:'room-state',room:{id:r.id,title:r.title,pickedId:r.pickedId,thumb:r.thumb,clients:r.clients.size}}));broadcast(r,{type:'room-users',count:r.clients.size});return}if(m.type==='room-event'&&ws.roomId){const r=rooms.get(ws.roomId);if(!r)return;const e=m.event||{};if(e.kind==='chat')broadcast(r,{type:'room-event',event:{kind:'chat',name:String(e.name||'Amigo').slice(0,40),text:String(e.text||'').slice(0,1000)}},ws);if(e.kind==='playback')broadcast(r,{type:'room-event',event:{kind:'playback',action:e.action==='pause'?'pause':'play',time:Number(e.time)||0}},ws)}});ws.on('close',()=>{if(ws.roomId&&rooms.has(ws.roomId)){const r=rooms.get(ws.roomId);r.clients.delete(ws);broadcast(r,{type:'room-users',count:r.clients.size});if(!r.clients.size)setTimeout(()=>{const x=rooms.get(r.id);if(x&&!x.clients.size)rooms.delete(r.id)},600000)}})});
app.get('/health',(q,s)=>s.json({ok:true,app:'Namaguederaz'}));app.get('/api/rooms',(q,s)=>s.json(list()));
app.post('/api/rooms',(q,s)=>{const b=q.body||{},title=String(b.title||'').trim(),pickedId=String(b.pickedId||'').trim();if(!title||!pickedId)return s.status(400).json({error:'Título e vídeo são obrigatórios'});const r={id:id(),title:title.slice(0,100),pickedId:pickedId.slice(0,50),thumb:String(b.thumb||''),public:b.public!==false,clients:new Set(),createdAt:Date.now()};rooms.set(r.id,r);s.json({id:r.id,title:r.title,pickedId:r.pickedId,thumb:r.thumb,public:r.public})});
app.post('/api/rooms/:id/join',(q,s)=>{const r=rooms.get(q.params.id);if(!r)return s.status(404).json({error:'Sala não encontrada ou encerrada'});s.json({id:r.id,title:r.title,pickedId:r.pickedId,thumb:r.thumb,public:r.public,clients:r.clients.size})});
app.get('/api/youtube/search',async(q,s)=>{try{const term=String(q.query.q||'').trim(),key=process.env.YOUTUBE_API_KEY;if(!term)return s.status(400).json({error:'Digite o que deseja pesquisar'});if(!key)return s.status(503).json({error:'Busca do YouTube indisponível: configure YOUTUBE_API_KEY no Render.'});const u=new URL('https://www.googleapis.com/youtube/v3/search');u.searchParams.set('part','snippet');u.searchParams.set('q',term);u.searchParams.set('type','video');u.searchParams.set('regionCode','BR');u.searchParams.set('relevanceLanguage','pt');u.searchParams.set('maxResults','12');u.searchParams.set('key',key);const r=await fetch(u),d=await r.json();if(!r.ok)return s.status(r.status).json({error:d?.error?.message||'Erro na busca do YouTube'});s.json({items:(d.items||[]).filter(x=>x.id?.videoId).map(x=>({videoId:x.id.videoId,title:x.snippet.title,channelTitle:x.snippet.channelTitle,thumb:x.snippet.thumbnails?.high?.url||x.snippet.thumbnails?.medium?.url||x.snippet.thumbnails?.default?.url}))})}catch(e){s.status(500).json({error:'Erro ao consultar o YouTube'})}});
server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Namaguederaz online'));
